on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install devtools dependencies
        run: |
          sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
        shell: bash

      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("distill")
        shell: Rscript {0}

      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.