on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install Rsync
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y rsync

      - name: Install devtools dependencies
        run: |
          sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
        shell: bash

      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("distill")
          writeLines(sprintf('R-%i.%i', getRversion()$major, getRversion()$minor), '.github/R-version')
          writeLines(Sys.getenv('AI_BLOG_PANDOC_VERSION'), '.github/pandoc-version')
        shell: Rscript {0}

      - name: Cache R Packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('.github/R-version') }}
          restore-keys: ${{ hashFiles('.github/R-version') }}

      - name: Cache Build Artifacts
        uses: actions/cache@v2
        with:
          path: /tmp/_posts
          key: ${{ hashFiles('.github/pandoc-version') }}-${{ hashFiles('.github/R-version') }}

      - name: Render Posts
        run: |
          rm -rf docs/
          set -x
          mkdir docs
          for file in $(find _posts -type f -name '*.Rmd')
          do
            (\
              diff -q {,/tmp/}"${file}" && \
                rsync -rv {/tmp/,}$(dirname "${file}")/ \
            ) || \
              Rscript -e "rmarkdown::render('${file}')"
          done
          rm -rf /tmp/_posts
          cp -r _posts /tmp
        shell: bash

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.